VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "vbaSAPGUIObjectInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public ObjectPath
Public ObjectName
Public ObjectValue
Public SAPObjectType 'String (Obj.ObjectType)
Public SAPObjectTypeAsNumber '(Obj.ObjectTypeAsNumber)
Public BusinessObjectType '(Criteria Button, Label-Field, Label-To, Low Value, High Value)
Public BaseName
Public Changeable

